Specifyapp/parsers

.github/workflows/continuous-integration-workflow.yml, .gitignore, README.md, jest.config.js, package.json
=> improvement(badges): add badges

parsers/pascalcasify/README.md, parsers/pascalcasify/pascalcasify.parser.ts, parsers/pascalcasify/pascalcasify.spec.ts
Add PascalCase parser
It just do a simple `_.flow(_.camelCase, _.upperFirst)(token[key])` like camelcase parser
No linear ticket
=> feat(parsers): add PascalCase parser

parsers/to-css-custom-properties/to-css-custom-properties.parser.ts, parsers/to-css-custom-properties/to-css-custom-properties.spec.ts, parsers/to-css-custom-properties/tokens/gradient.ts
- fix gradient for `to-css-custom-properties`
=> fix(to-css-custom-properties): fix gradient

jest.config.js, parsers/to-css-custom-properties/tokens/shadow.ts, parsers/to-dsp/tokens/shadow.ts, parsers/to-jss/tokens/shadow.ts, types/tokens/Shadow.ts
Add the spread option and use it in parsers to-css-custom-properties, to-jss and to-dsp
=> feat(tokens): add spread option in the shadow token

parsers/convert-font/convert-font.parser.ts, parsers/convert-font/convert-font.spec.ts, seeds.json, tests/global.ts, types/tokens/Font.ts
- Add management of missing font.
=> fix(convert-font): prevent error when font file missing

libs/size-manipulation.ts, parsers/px-to-rem/README.md, parsers/px-to-rem/px-to-rem.parser.ts, parsers/px-to-rem/px-to-rem.spec.ts, parsers/to-css-textStyle/README.md, parsers/to-css-textStyle/to-css-textStyle.parser.ts, parsers/to-css-textStyle/to-css-textStyle.spec.ts, seeds.ts
- Add a parser to generate text styles in css.
=> feat(to-css-textStyle): add parser

parsers/to-scss-mixin-textStyle/README.md, parsers/to-scss-mixin-textStyle/to-scss-mixin-textStyle.parser.ts, parsers/to-scss-mixin-textStyle/to-scss-mixin-textStyle.spec.ts
- add `to-scss-mixin-textStyle`
=> feat(to-scss-mixin-textStyle): add parser

parsers/camelcasify/camelcasify.parser.ts, parsers/convert-font/convert-font.parser.ts, parsers/kebabcasify/kebabcasify.parser.ts, parsers/pascalcasify/pascalcasify.parser.ts, parsers/pick/pick.parser.ts, parsers/snakecasify/snakecasify.parser.ts, parsers/sort-by/sort-by.parser.ts, parsers/suffix-by/suffix-by.parser.ts, parsers/to-css-custom-properties/to-css-custom-properties.parser.ts, parsers/to-css-font/to-css-font.parser.ts, parsers/to-dsp/to-dsp.parser.ts, parsers/to-jss/to-jss.parser.ts, types/tokens/Font.ts, types/tokens/TextStyle.ts
- Fix types due to update of typescript
Resolves DEV2-549
=> fix(type): update type due to update of typescript

parsers/to-css-custom-properties/to-css-custom-properties.spec.ts, types/tokens/Font.ts
- Fix font type.
Resolves DEV2-573
=> fix(to-css-custom-properties): fix font types

README.md, parsers/svgo/README.md
Update main README + Add svgo in usable libraries
=> feat(): Update main README + Add svgo in usable libraries

.github/workflows/continuous-integration-workflow.yml, parsers/svgo/svgo.parser.ts, parsers/svgo/svgo.spec.ts
- Merge value instead of replace
=> fix(svgo): merge value instead of reattribute

libs/list-paths-by-pattern.ts, parsers/px-to-rem/README.md, parsers/round-number/README.md, parsers/round-number/round-number.parser.ts, parsers/round-number/round-number.spec.ts, parsers/to-css-text-style/to-css-text-style.spec.ts, parsers/to-scss-mixin-text-style/to-scss-mixin-text-style.spec.ts, seeds.ts
Create a parsers that allow to round any measurement tokens.
You will be able to specify the number of decimals and the round mode.
=> feat(parsers): add round-number parser

README.md
=> Add contributor badge

parsers/camelcasify/README.md, parsers/convert-font/README.md, parsers/kebabcasify/README.md, parsers/link-design-tokens/README.md, parsers/name-assets-files-by-pattern/README.md, parsers/pascalcasify/README.md, parsers/pick/README.md, parsers/px-to-rem/README.md, parsers/replace-string/README.md, parsers/replace-string/replace-string.parser.ts, parsers/replace-string/replace-string.spec.ts, parsers/round-number/README.md, parsers/snakecasify/README.md, parsers/sort-by/README.md, parsers/suffix-by/README.md, parsers/svgo/README.md, parsers/to-css-custom-properties/README.md, parsers/to-css-font-import/README.md, parsers/to-css-text-style/README.md, parsers/to-jss/README.md, parsers/to-scss-mixin-text-style/README.md, parsers/to-theme-ui/README.md, tests/fixtures/seeds.json
- Add parser `string-replacer`
=> feat(string-replacer): add parser

parsers/to-jss/to-jss.parser.ts
- Allow unknown keys for input data for to-jss
=> fix(to-jss): fix input type

parsers/svgo/svgo.parser.ts, parsers/svgo/svgo.spec.ts, parsers/to-css-text-style/to-css-text-style.parser.ts, parsers/to-css-text-style/to-css-text-style.spec.ts, parsers/to-scss-mixin-text-style/to-scss-mixin-text-style.parser.ts, parsers/to-scss-mixin-text-style/to-scss-mixin-text-style.spec.ts, parsers/to-tailwind/to-tailwind.spec.ts, parsers/to-tailwind/tokens/textStyle.ts, parsers/to-theme-ui/tokens/font.ts, types/tokens/Font.ts
Fix text style naming : We used the Font Family instead of the token name when generating files using our text styles
Resolves DEV-853
=> fix(text-styles): fix text style naming

parsers/convert-font/README.md, parsers/convert-font/convert-font.parser.ts, parsers/convert-font/convert-font.spec.ts, parsers/to-css-font-import/README.md, parsers/to-css-font-import/to-css-font-import.parser.ts, parsers/to-css-font-import/to-css-font-import.spec.ts, parsers/to-tailwind/README.md
Update default font file formats + Update READMEs
=> Update default font file formats + Update READMEs

parsers/to-scss-map/README.md
=> fix(to-scss-map): fix doc

parsers/pick/README.md, parsers/pick/pick.parser.ts, parsers/pick/pick.spec.ts, parsers/suffix-by/README.md, parsers/suffix-by/suffix-by.parser.ts, parsers/suffix-by/suffix-by.spec.ts
- Add an option to pick to allow flattening.
- Add an option to suffix-by to allow usage of template in suffix option.
=> improvement(pick_suffix-by): add options

parsers/convert-font/convert-font.parser.ts, parsers/convert-font/convert-font.spec.ts, tests/fixtures/seeds.json
Convert-font:
- add format in value 
- add fileName in value
- prevent mutation of name
=> fix(convert-font): add fileName to font

libs/template.ts, parsers/convert-font/README.md, parsers/convert-font/convert-font.parser.ts, parsers/global-libs.ts, parsers/pascalcasify/pascalcasify.parser.ts, parsers/svg-to-jsx/README.md, parsers/svg-to-jsx/svg-to-jsx.parser.ts, parsers/svg-to-jsx/svg-to-jsx.spec.ts, parsers/svgo/README.md, parsers/to-css-custom-properties/README.md, parsers/to-css-custom-properties/to-css-custom-properties.parser.ts, parsers/to-css-font-import/README.md, parsers/to-css-font-import/to-css-font-import.parser.ts, parsers/to-css-text-style/README.md, parsers/to-css-text-style/to-css-text-style.parser.ts, parsers/to-jss/README.md, parsers/to-jss/to-jss.parser.ts, parsers/to-scss-map/README.md, parsers/to-scss-map/to-scss-map.parser.ts, parsers/to-scss-mixin-text-style/README.md, parsers/to-scss-mixin-text-style/to-scss-mixin-text-style.parser.ts, parsers/to-tailwind/README.md, parsers/to-tailwind/to-tailwind.parser.ts, parsers/to-theme-ui/README.md, parsers/to-theme-ui/to-theme-ui.parser.ts, tests/seeds.ts, tests/tests/pipe/round-number_link-design-tokens_to-theme-ui.spec.ts, tests/tests/pipe/svgo_svg-to-jsx.spec.ts
=> feat(svg-to-jsx): add svg-to-jsx

libs/list-paths-by-pattern.ts, tests/tests/libs/list-paths-by-pattern.spec.ts
- Refacto + add tests to lib: `list-paths-by-pattern`
=> chore(list-paths-by-pattern): refacto + add tests

parsers/omit/README.md, parsers/omit/omit.parser.ts, parsers/omit/omit.spec.ts
=> feat(omit): add parser omit

parsers/to-theme-ui/to-theme-ui.parser.ts, parsers/to-theme-ui/to-theme-ui.spec.ts
- fix freeze option in theme-ui
=> fix(theme-ui): fix freeze option

parsers/camelcasify/README.md, parsers/filter/README.md, parsers/filter/filter.parser.ts, parsers/filter/filter.spec.ts
=> feat(filter): add filter parser

parsers/filter/filter.spec.ts, parsers/name-assets-files-by-pattern/name-assets-files-by-pattern.spec.ts, parsers/suffix-by/suffix-by.spec.ts, parsers/svgo/svgo.parser.ts, parsers/svgo/svgo.spec.ts, parsers/to-dsp/to-dsp.spec.ts, parsers/to-react-native/__snapshots__/to-react-native.spec.ts.snap, tests/fixtures/seeds.json
Only svg vector can be used for svgo tool.
Resolves DEV-1086
=> fix(svgo): Allow to use svgo when there is svg and pdf

package.json, parsers/svg-to-jsx/svg-to-jsx.parser.ts, parsers/svg-to-jsx/svg-to-jsx.spec.ts, parsers/svg-to-jsx/svg-to-jsx.type.ts, tests/tests/pipe/svgo_svg-to-jsx.spec.ts, tsconfig.json, yarn.lock
Switch svg attribute name to kebabCase
Resolves DEV-1088
=> fix(svg-to-jsx): Attribute in camelCase

parsers/svg-to-jsx/svg-to-jsx.parser.ts, parsers/svg-to-jsx/svg-to-jsx.spec.ts
What it does
Replace maskunits attribute in maskUnits
Linear ticket
Resolves DEV-1088
=> fix(svg-to-jsx): maskunits attribute must be maskUnits in jsx

parsers/svg-to-jsx/svg-to-jsx.parser.ts
- Support `gradientunits` `gradienttransform` in svg-to-jsx
=> fix(svg-to-jsx): support gradientunits and gradienttransform

parsers/filter/README.md
=> fix(filter): typo

parsers/svg-to-jsx/README.md, parsers/svg-to-jsx/svg-to-jsx.parser.ts, parsers/svg-to-jsx/svg-to-jsx.spec.ts
- Add `isTsx` option.
Fix #114
=> feat(svg-to-jsx): add isTsx option

parsers/to-tailwind/README.md, parsers/to-tailwind/to-tailwind.parser.ts, parsers/to-tailwind/to-tailwind.spec.ts, parsers/to-tailwind/to-tailwind.type.ts, parsers/to-tailwind/tokens/border.ts, parsers/to-tailwind/tokens/color.ts, parsers/to-tailwind/tokens/depth.ts, parsers/to-tailwind/tokens/duration.ts, parsers/to-tailwind/tokens/gradient.ts, parsers/to-tailwind/tokens/index.ts, parsers/to-tailwind/tokens/measurement.ts, parsers/to-tailwind/tokens/opacity.ts, parsers/to-tailwind/tokens/shadow.ts, parsers/to-tailwind/tokens/textStyle.ts, types/utils/utils.ts
- Add options `splitBy` to parser to-tailwind.
=> feat(to-tailwind): add options splitBy

LICENSE, package.json
- Switch license from markdown to text
- Update format of license in package.json
=> chore(*): update license

parsers/to-scss-map/to-scss-map.spec.ts
// Quick description
// If the linear ticket needed dev on others projects, put the PRs link here
Resolves [DEV-XXX]
=> chore(to-scss-map): fix test

README.md
=> docs(readme): add readme image

package.json, parsers/replace-string/README.md, parsers/replace-string/replace-string.parser.ts, parsers/replace-string/replace-string.spec.ts, yarn.lock
- Allow applying replace-string with string type in inputDataType
=> feat(replace-string): Allow applying replace-string with string type in inputDataType

parsers/to-style-dictionary/README.md
Update to-style-dictionary README
=> feat(parsers): Update to-style-dictionary README

parsers/convert-font/README.md, parsers/name-assets-files-by-pattern/README.md, parsers/svg-to-jsx/README.md, parsers/svgo/README.md, parsers/to-dsp/README.md, parsers/to-scss-map/README.md, parsers/to-style-dictionary/README.md
Update all parsers README to help users understand what they should write in the parent’s rule path property
Resolve #124
=> feat(parsers): Update several parsers README

parsers/to-style-dictionary/README.md
Fix to-style-dictionary README
=> fix(to-style-dictionary): Fix README

README.md, parsers/camelcasify/README.md, parsers/filter/README.md, parsers/kebabcasify/README.md, parsers/to-jss/README.md
=> feat(): Improve parsers documentation

README.md
Add dynamic light/dark theme assets in main README
=> Add color theme img in readme

parsers/to-react-native/README.md
Fix usage config example
Resolves DEV-1654
=> improvement(react-native): Fix usage config example

parsers/to-style-dictionary/to-style-dictionary.parser.ts
- Fix types of to-style-dictonary
=> fix(to-style-dictionary): fix types

parsers/to-css-custom-properties/README.md
Enhance doc on default kebabcase transformation on to-css-custom-properties
Resolves DEV-1704
=> chore(to-css-custom-properties): Improve doc

README.md
=> fix(parsers): Fix typo

package.json, parsers/to-flutter/README.md, parsers/to-flutter/__snapshots__/to-flutter.spec.ts.snap, parsers/to-flutter/to-flutter.parser.ts, parsers/to-flutter/to-flutter.spec.ts, parsers/to-flutter/tokens/color.ts, parsers/to-flutter/tokens/measurement.ts, yarn.lock
Add Flutter parser
Resolves DEV-1805
=> feat(parsers): Add Flutter parser

parsers/link-design-tokens/README.md, parsers/svg-to-jsx/README.md
=> improvement(parsers): Fix typos

README.md
Include links that are the most important for our community.
Resolves [DEV-1887]
=> content(parsers): Update parsers main README

parsers/inline-css-variables-in-svg/README.md
Update `inline-css-variables-in-svg` parser README.
=> improvements(inline-css-variables-in-svg): Update parser README - DEV-2484

parsers/to-flutter/README.md
=> fix(): Fix to-flutter parser README

parsers/to-style-dictionary/to-style-dictionary.spec.ts, parsers/to-style-dictionary/tokens/duration.ts
Convert all duration in ms to respect the style dictionary spec.
=> fix(to-style-dictionary): set all duration in ms

package.json, parsers/to-flutter/README.md, parsers/to-flutter/__snapshots__/to-flutter.spec.ts.snap, parsers/to-flutter/to-flutter.parser.ts, parsers/to-flutter/to-flutter.spec.ts, parsers/to-flutter/tokens/color.ts, parsers/to-flutter/tokens/measurement.ts, parsers/to-flutter/tokens/textStyle.ts
This PR adds `textStyle` conversion and adds types to variables
=> [Feature] to-flutter: text styles and types

parsers/to-style-dictionary/to-style-dictionary.spec.ts, parsers/to-style-dictionary/tokens/font.ts
Add `fontWeight` in font assets exported by `to-style-dictionary` parser.
=> feat(parsers): Update to-style-dictionary parser - DEV-2828

parsers/to-theme-ui/README.md
Fix advanced usage example in to-theme-ui README
=> fix(to-theme-ui): Fix README - DEV-2937

parsers/to-style-dictionary/README.md, parsers/to-style-dictionary/__snapshots__/to-style-dictionary.spec.ts.snap, parsers/to-style-dictionary/to-style-dictionary.parser.ts, parsers/to-style-dictionary/to-style-dictionary.spec.ts, parsers/to-style-dictionary/to-style-dictionary.type.ts, parsers/to-style-dictionary/tokens/bitmap.ts, parsers/to-style-dictionary/tokens/border.ts, parsers/to-style-dictionary/tokens/color.ts, parsers/to-style-dictionary/tokens/depth.ts, parsers/to-style-dictionary/tokens/duration.ts, parsers/to-style-dictionary/tokens/font.ts, parsers/to-style-dictionary/tokens/measurement.ts, parsers/to-style-dictionary/tokens/opacity.ts, parsers/to-style-dictionary/tokens/shadow.ts, parsers/to-style-dictionary/tokens/textStyle.ts, parsers/to-style-dictionary/tokens/vector.ts, parsers/to-style-dictionary/utils/setDescription.ts
- Add option to add description
=> feat(to-style-dictionary): add description option

parsers/to-css-custom-properties/__snapshots__/to-css-custom-properties.spec.ts.snap, parsers/to-css-custom-properties/to-css-custom-properties.parser.ts, parsers/to-css-custom-properties/to-css-custom-properties.spec.ts, parsers/to-css-custom-properties/tokens/index.ts, parsers/to-css-custom-properties/tokens/textStyle.ts
This PR adds the `textStyle` token to the parser `to-css-custom-properties`
=> feat(to-css-custom-properties): Added the text style
