- parsers/to-css-custom-properties/tokens/border.ts
Value for border type was given in lowercase by Specify API (like in Figma API i suppose), but by convention it should be in lowercase.
StyleLint with default config will throw an error ([see exemple here](https://stylelint.io/demo#N4Igxg9gJgpiBcIBGEBOtXwAQHYAOAHlgMoDyAMgJIAiWqA5kgIYAUAjAJwcA0WALAA5eAZhy8ADADoOwgJQBuENxABnAJ4A7AC5MCCcCpVLwEDQDMAlvX3AAOhqxZbIVAFcANjBXPsdh46cQJi0AWjdPEI0IENcNAGsogHcNHywtNxhuewDApHcIMDjI6JgAWzwtNVT010zsgOdIfNRikIsNADcmdwsoEIALGAJqjKz-R0aIUtKYbVayiqqENNH6iZBYMHcmVGCLUxC8gqKokKhXPB6wYJgQvFQIPBhULQsvVIBtNYCauvGAvw5HLOKxRVAwT7fIGBSAaFQwMCuV4dW7nS4Wa5aLwhRIWLT9M4WMxmZ6zUJddy1bwgKEBAC6tIAvt86WNgRsEdtdq8DkdCq0VP00PimBo+vdHs9KiEICjUKheu9lr82Q0QGZTKEzExShZ3GpWmirjdIjqldgVd9nBq5trdfrWrrDO16CF6LNnhiQna9Qa4jA1Ik0FARrVVeszLEwDyNCFru4wK12hTeqG-uzIxpo-tY-HE6dYio8EwwDA+pLuWg …
> fix(parsers): border type value in lowercase for css parser

- parsers/to-css-custom-properties/to-css-custom-properties.spec.ts
- parsers/to-css-custom-properties/tokens/shadow.ts
It fix shadow values given by `shadow.ts`, actually if shadow is not an inner shadow (most of cases) space between `'inset'` and `${x.measure}` is kept in value as it is hardcoded in template string.
shadow **`value`** output:
> before:
`" 37px 71px 2px rgba(144, 63, 6, 0.28)"` or `"inset 37px 71px 2px rgba(144, 63, 6, 0.28)"`
> after:
`"37px 71px 2px rgba(144, 63, 6, 0.28)"` or `"inset 37px 71px 2px rgba(144, 63, 6, 0.28)"`
❌
> fix(parsers): remove extra space at beginning of shadow value

- parsers/to-jss/README.md
- parsers/to-jss/to-jss.parser.ts
It add exportDefault option for to-jss parser
default value: `true`
result as
``` js
const ${jssObjectName} = {
...
};
export default ${jssObjectName};
```
// If the linear ticket needed dev on others projects, put the PRs link here
❌
> Add exportDefault option for to-jss parser

- parsers/to-jss/to-jss.parser.ts
- parsers/to-jss/to-jss.spec.ts
Hello ! 
I have made some modifications to the `to-jss` parser to improve the output possibilities in terms of module support:
- CommonJs support (`module.exports = themeName` & `module.exports = { themeName }`)
- When `exportDefault` is set to `false` it makes an `exports const` rather than not exporting. Imho, a generated file without an export will be painful to use because each time we update it, we'll have to add an export manually
- Made test as well (tell me if the naming is not the right one)
> feat(to-jss): Added commonjs support and 'export only' as well

- parsers/to-css-font/README.md
Fixed a small issue (typo) in the readme that shifted a line in the options table.
> Fix README: to-css-font

- types/tokens/TextStyle.ts
Fix text styles typing for parsers
Vertical text align should allow value `center`
> fix(text-styles): fix text styles typing for parsers

- parsers/to-jss/README.md
- parsers/to-jss/to-jss.parser.ts
- parsers/to-jss/tokens/textStyle.ts
It add following features to `to-jss` parser:
- `letterSpacing` property is added text style tokens when `classObject` format is passed to `textStyleFormat`
- `isVectorFileType` and `isBitmapFileType` added to `formatConfig` options to remove filetype in token names
- `isBitmapScale` added to `formatConfig` options to remove  all scale stuff like `@2x` from the bitmap token names
`isVectorFileType`, `isBitmapFileType` and `isBitmapScale` are all setted to `true` by default.
tested all options on `@station/NewThemeLight` repo with json provided by Specify API (mostly to test `letterSpacing` and scale/filetype in DT names which are not included in sample file used by tests)
[ds.json.zip](https://github.com/Specifyapp/parsers/files/6045611/ds.json.zip)
Resolves nothing
> feat: add vector/bitmap name format options + letterSpacing

- types/tokens/Font.ts
Fix the typing of the Font Token Value (changed due to the fix that allows to dl the font file from the CLI without using any parsers)
> fix(font): fix font dl without parser

- parsers/convert-font/README.md
Update convert-font README todd `fontPostScriptName` property as an option for the `fileNameKey` property.
> Update convert-font README

- parsers/to-style-dictionary/to-style-dictionary.parser.ts
- parsers/to-style-dictionary/to-style-dictionary.spec.ts
Fix to-style-dictionary. There was a bug where no tokens were created when we didn't use any splitBy option
> fix(to-style-dictionary): fix splitBy option

- parsers/to-style-dictionary/to-style-dictionary.spec.ts
- parsers/to-style-dictionary/tokens/bitmap.ts
- parsers/to-style-dictionary/tokens/font.ts
- parsers/to-style-dictionary/tokens/vector.ts
Fix a bug where when assetsBaseDirectory is set, the name of the asset is not appended to the string value.
Example :
`assetsBaseDirectory.fonts = 'fonts/'`
expected result : 
```js
myfont: {
ttf: { 
value: 'fonts/myfont.ttf'
}
}
```
before fix : 
```js
myfont: {
ttf: { 
value: 'fonts/'
}
}
```
> fix(style-dictionary): fix assets base dir

- parsers/svg-to-jsx/svg-to-jsx.parser.ts
- parsers/svg-to-jsx/svg-to-jsx.spec.ts
Replace viewbox attribute in viewBox
Resolves DEV-1088
> fix(svg-to-jsx): viewbox attribute must be viewBox in jsx

- parsers/to-tailwind/README.md
- parsers/to-tailwind/to-tailwind.parser.ts
- parsers/to-tailwind/to-tailwind.spec.ts
- parsers/to-tailwind/to-tailwind.type.ts
- parsers/to-tailwind/tokens/border.ts
- parsers/to-tailwind/tokens/color.ts
- parsers/to-tailwind/tokens/depth.ts
- parsers/to-tailwind/tokens/duration.ts
- parsers/to-tailwind/tokens/gradient.ts
- parsers/to-tailwind/tokens/index.ts
- parsers/to-tailwind/tokens/measurement.ts
- parsers/to-tailwind/tokens/opacity.ts
- parsers/to-tailwind/tokens/shadow.ts
- parsers/to-tailwind/tokens/textStyle.ts
- parsers/to-tailwind/utils/getNameFormatterFunction.ts
Adds a new `renameKeys` to the parser configuration. So that, each Tailwind theme key can get overwritten using a template pattern.
```json
{
"name": "to-tailwind",
"options": {
"renameKeys": {
"colors": "custom-color-{{name}}",
"spacing": "custom-spacing-{{name}}"
},
"formatName": "kebabCase",
"formatConfig": {
"objectName": "extend",
"module": "commonjs"
}
}
}
```
**Input**
```json
[
{
"name": "primary",
"value": {
"a": 1,
"b": 255,
"g": 189,
"r": 198
},
"type": "color"
},
{
"name": "base-space-01",
"value": {
"unit": "px",
"measure": 4
},
"type": "measurement"
}
]
```
**Output**
```js
const extend = {
colors: {
'custom-color-primary': '#C6BDFF',
},
spacing: {
'custom-spacing-base-space-01': '4px',
},
};
module.exports = extend;
```
Resolves DEV-1096
> feat(to-tailwind): support pattern renaming for Tailwind theme keys

- parsers/to-react-native/README.md
- parsers/to-react-native/__snapshots__/to-react-native.spec.ts.snap
- parsers/to-react-native/to-react-native.parser.ts
- parsers/to-react-native/tokens/bitmap.ts
Only require-style imports can resolve @2x and @3x bitmap variants. 
See https://reactnative.dev/docs/images#static-image-resources
> fix(to-react-native): use require-style imports on bitmaps

- parsers/to-style-dictionary/to-style-dictionary.spec.ts
- parsers/to-style-dictionary/tokens/font.ts
- Fix bug that generates only one font format instead of those that have been defined in options
> fix(to-style-dictionary): allow to generate all font formats described in the option fontFormat.

- parsers/to-react-native/__snapshots__/to-react-native.spec.ts.snap
- parsers/to-react-native/tokens/textStyle.ts
If a `textStyle` token has no color, the color should be omitted from the react native theme as well. 
The color defaulted to `rgb(0, 0, 0)`, which is not desired
> fix(to-react-native): don't fallback to black if no text color is defined

- parsers/filter/filter.parser.ts
- parsers/filter/filter.spec.ts
Currently you cannot filter on a non-string values: 
```
Parser Error: Runtime Error at filter parser: valueToCheck.match is not 
a function
```
This PR fixes that by converting to a string first.
Example config: 
```ts
{
name: 'Only return @2x variants',
path: 'bitmaps',
filter: { types: ['bitmap'] },
parsers: [
{
name: 'filter',
options: {
key: 'meta.dimension',
regex: {
pattern: '2',
},
},
}
],
};
```
Resolves [DEV-XXX]
> fix(filter): convert value to string before matching regex

- parsers/to-react-native/README.md
- parsers/to-react-native/__snapshots__/to-react-native.spec.ts.snap
- parsers/to-react-native/to-react-native.spec.ts
- parsers/to-react-native/tokens/bitmap.ts
- parsers/to-react-native/tokens/vector.ts
- parsers/to-react-native/util/path.ts
This reverts commit d39e4e2d3d078f711c99f973b8b304e217f6b058 (https://github.com/Specifyapp/parsers/pull/107). For assets `import` works exactly the same as `require`, so it is cleaner when everything uses the same import method.
This is non-breaking.
https://stackoverflow.com/questions/73475946/react-native-images-require-vs-import/73633110
> feat(to-react-native): use import instead of require.

- parsers/to-react-native/README.md
- parsers/to-react-native/__snapshots__/to-react-native.spec.ts.snap
- parsers/to-react-native/to-react-native.parser.ts
- parsers/to-react-native/to-react-native.spec.ts
Adds the option `formatKeys` on the `to-react-native` parser, allowing you to select between kebab, camel, snake, and pascal casing, defaulting to camel casing.
> feat(to-react-native): allow ability to format keys

- parsers/to-react-native/README.md
- parsers/to-react-native/__snapshots__/to-react-native.spec.ts.snap
- parsers/to-react-native/to-react-native.parser.ts
- parsers/to-react-native/to-react-native.spec.ts
This pull request adds the `isTypescript` option to the `to-react-native` parser, which supplies `typescript` to prettier as the parser, as well as adds `as const` to the tail-end of the object in order to fix issues with union type incompatibilities in TypeScript projects (ie., `fontWeight`).
> feat(to-react-native): export style object as const

- parsers/to-typescript-definition/README.md
- parsers/to-typescript-definition/__snapshots__/to-typescript-definition.spec.ts.snap
- parsers/to-typescript-definition/to-typescript-definition.parser.ts
- parsers/to-typescript-definition/to-typescript-definition.spec.ts
This parser converts tokens into Typescript types. The token type is the type name, and the tokens values are the possible values of the type
Also for the `README`, I filled every possible cases in the `Option` part. I'm not sure if it's 100% relevant, but I don't think `typesNamesMapping.tokenType` would be really explicit
> [Feature] Created `to-typescript-definition`  parser

- parsers/to-flutter/__snapshots__/to-flutter.spec.ts.snap
- parsers/to-flutter/tokens/color.ts
Generated colors were broken, the opacity was supposed to be at begining of the color rather than at the end
> [Fix] to-flutter: Colors opacity

- parsers/to-css-text-style/to-css-text-style.parser.ts
- parsers/to-css-text-style/to-css-text-style.spec.ts
Only execute `to-css-text-style` parser on `textStyle` token type.
> feat(to-css-text-style): Filter on textStyle tokens - DEV-2829

- README.md
- parsers/to-tailwind/README.md
- parsers/to-tailwind/to-tailwind.parser.ts
- parsers/to-tailwind/to-tailwind.spec.ts
- parsers/to-tailwind/to-tailwind.type.ts
- parsers/to-tailwind/tokens/index.ts
- parsers/to-tailwind/utils/getClassNameAsCSSVariable.ts
This PR adds in support for outputting CSS variables as the utility class value in the Tailwind theme. This enables functionality such as dark/light mode to be possible and a big selling point of Design Tokens with a single tailwind theme but dynamic values for each key in the theme. This also empowers use cases such as whitelabelling of applications with the switchability of underlying styling but a consistent codebase.
- I have added some tests that checks for the correctly formatted `var()` for each token being in the output. I had to mock the lodash mixin as for some reason it wasn't working in Jest and no other tests in the repository were using the pascalCase formatting mixin so I didn't have any other examples to follow. The tests also ensure the formatted is correct for each type …
> feat(to-tailwind): add in css variables support

- parsers/to-css-custom-properties/__snapshots__/to-css-custom-properties.spec.ts.snap
- parsers/to-css-custom-properties/to-css-custom-properties.spec.ts
- parsers/to-css-custom-properties/tokens/textStyle.ts
This PR updates the text-style font-family and replace it by `fontPostScriptName`
> refactor(to-css-custom-properties): Replaced font name by fontPostScriptName
